
version: "3.9"
services:
  db:
    image: mysql:8.4
    container_name: otp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: otp_service
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build: .
    container_name: otp_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: otp_service
    ports:
      - "3000:3000"
    command: node app.js

volumes:
  db_data:
